version: 0.2

env:
  variables:
    APP_URL: "https://phopixel.com"

phases:
  install:
    runtime-versions:
      nodejs: latest
      # php: 8.1
      # name: version
      # name: version
    commands:
      - apt-get update -y
      - apt-get install lsb-release ca-certificates apt-transport-https software-properties-common -y
      - add-apt-repository ppa:ondrej/php
      - apt-get update
      - apt-get install -y php8.1
      - apt-get install -y php8.1-intl php8.1-zip php8.1-simplexml php8.1-dom php8.1-mbstring php8.1-curl php8.1-mysql php8.1-sqlite php8.1-gd php8.1-imagick
      #pre_build:
      #commands:
      # - command
  build:
    commands:
      - cp .env.example .env
      - npm install
      - npm run production
      - curl -sS https://getcomposer.org/installer | php
      - /usr/bin/php8.1 ./composer.phar install
      # - /usr/bin/php8.1 vendor/bin/phpunit
  post_build:
    commands:
      - cp -R ${CODEBUILD_SRC_DIR_codedeploy}/. .
      - rm -rf .git;
      - rm -f .php_cs;
      - rm -rf tests;
      - rm -rf composer.phar;
      - rm -rf composer.lock;
      - rm -rf .env.example;
      - rm -rf node_modules
      # - command
artifacts:
  files:
    - '*/'
    # - location
    # - location
    #name: $(date +%Y-%m-%d)
    #discard-paths: yes
    #base-directory: location
    #cache:
    #paths:
    # - paths
